// Auto-generated adaptive key table. Do not edit directly.
#include <quantum.h>
#include "processAdaptive.h"

const struct _adaptive_key adaptive_keys[] PROGMEM = {
    {KC_W, KC_M, KC_G, "lml"},
    {KC_M, KC_W, KC_M, "mpl"},

    {KC_P, KC_D, 0, "pwd"},
    {KC_P, KC_F, 0, "ps"},
    {KC_K, KC_G, 0, "kl"},
    {KC_M, KC_G, 0, "lg"},
    {KC_J, KC_G, 0, "jpg"},
    {KC_W, KC_G, 0, "wd"},
    {KC_K, KC_H, 0, "kn"},
    {KC_G, KC_J, 0, "gth"},
    {KC_V, KC_J, 0, "vl"},
    {KC_W, KC_J, 0, "wl"},
    {KC_M, KC_K, 0, "lk"},
    {KC_H, KC_K, 0, "nk"},
    {KC_N, KC_H, 0, "nd"},
    {KC_P, KC_L, 0, "pl"},
    {KC_B, KC_L, 0, "bl"},
    {KC_S, KC_L, 0, "sl"},
    {KC_G, KC_M, 0, "gl"},
    {KC_V, KC_M, 0, "vl"},
    {KC_W, KC_M, 0, "lm"},
    {KC_F, KC_P, 0, "sp"},
    {KC_D, KC_P, 0, "pg"},
    {KC_G, KC_V, 0, "gt"},
    {KC_M, KC_V, 0, "lv"},
    {KC_G, KC_W, 0, "gd"},
    {KC_M, KC_W, 0, "mp"},
    {KC_Y, KC_B, 0, "ib"},
    {KC_A, KC_E, 0, "au"},
    {KC_DOT, KC_SLASH, 0, ".com"},
    {KC_DOT, KC_DQUO, 0, ".edu"},
    {KC_DOT, KC_QUOTE, 0, ".org"},
    {KC_A, KC_QUOTE, 0, "au"},
    {KC_U, KC_QUOTE, 0, "ua"},
    {KC_E, KC_QUOTE, 0, "eo"},
    {KC_O, KC_QUOTE, 0, "oe"},
    {KC_A, KC_Z, 0, "au"},
    {KC_U, KC_Z, 0, "ua"},
    {KC_E, KC_Z, 0, "eo"},
    {KC_O, KC_Z, 0, "oe"},
    {KC_C, KC_HASH, 0, "cgi"},
    {KC_G, KC_HASH, 0, "gmail"},
    {KC_K, KC_HASH, 0, "quesnel"},
    {KC_P, KC_HASH, 0, "philippe"},
    {KC_DOT, KC_HASH, 0, "philippe.quesnel"},
    {KC_D, KC_HASH, 0, "device"},
    {KC_I, KC_HASH, 0, "integration\\"},
    {KC_S, KC_HASH, 0, "select * from "},

    {0, 0, 0, NULL}
};
